### ISSUE TITLE
Using datadog-firehose-nozzle on server that have limited internet access.

### ISSUE THREAD

**Issue by YunSangJun** [cloudfoundry/datadog-firehose-nozzle#15]
How to use datadog-firehose-nozzle on server that have limited internet access?.

In case of using datadog agent there is workaround as following link.
https://github.com/DataDog/dd-agent/wiki/Proxy-Configuration.

**Comment by iplay88keys** [comment]
@YunSangJun Can you use `NOZZLE_DATADOGURL` env variable to point to a [proxy](https://github.com/DataDog/dd-agent/wiki/Proxy-Configuration#using-the-agent-as-a-proxy) that you run? 

We're not sure what modifications you would like to see. We will keep this story in our icebox for our PM to review.

**Comment by YunSangJun** [comment]
Datadog client in datadog-firehose-nozzle can not send data directly to Datadog public url on my enviroment cause of firewall.

So i would like to send data via proxy as following workaround.
https://github.com/DataDog/dd-agent/wiki/Proxy-Configuration.

I tried to change datadog.api_url to proxy but it did not work. I found 404 error message on "/var /vcp/sys/log/" in datadog-firehose-nozzle VM.

The proxy status was ok when i curl to the proxy on datadog-firehose-nozzle VM 
curl -v http://proxy-node:17123/status 2>&1 | grep "200 OK"

<datadog nozzle bosh deployment file>
...
releases:
- name: datadog-firehose-nozzle
  version: '51'
...
properties:
  datadog:
    api_key: xxxxxxx
    #api_url: https://app.datadoghq-env.com/api/v1/series 
    api_url: http://proxy_node_ip:17123
    flush_duration_seconds: 15
    metric_prefix: datadog.nozzle.
...

**Comment by ahevenor** [comment]
@YunSangJun thanks for your patience. This got frozen in our icebox but I have scheduled it for review in our next planning meeting.

**Comment by mmessmore** [comment]
I have CF deployed inside a network where I need to go out a proxy to talk to the outside world.  I do this now by setting the environment variables for http_proxy and https_proxy, and then I make sure my CF domain is in the no_proxy environment variable so that the proxy is not used to avoid issues with websockets.

I'm running it with systemd right now as user/group firehose and installed in /home/firehose on the host.

```
[Unit]
Description=DataDog Firehose Nozzle
After=network.target

[Service]
Type=simple
User=firehose
Group=firehose
Environment=http_proxy=http://my.proxy.example.com:3128
Environment=https_proxy=http://my.proxy.example.com:3128
Environment=no_proxy=example.com
ExecStart=/home/firehose/bin/datadog-firehose-nozzle -config /home/firehose/config/datadog-firehose-nozzle.json
Restart=always

[Install]
WantedBy=multi-user.target
```

Your milage may vary
