### ISSUE TITLE
Point type is wrong

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/datadog-firehose-nozzle#21]
https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle/blob/master/datadogclient/datadog_client.go#L62

Datadog docs say the point value is `float32`. See: http://docs.datadoghq.com/api/?lang=console#overview:

> Note that the timestamp should be in seconds, must be current, and the numeric value is a 32bit float gauge-type value.

Just a heads up.

**Comment by ahevenor** [comment]
The source of truth repo has moved to: https://github.com/DataDog/datadog-firehose-nozzle Please re-open this ticket there if it is still an issue.
